### ISSUE TITLE
Nav dropdown link hover too light

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-portal#142]
Latest changes to hover styling for the `<a>` tags results in extremely low contrast colors while hovering. Try the following instead in `style.css`:

```css
#topnav a:not(.dropdown-item):hover {
  color: #c4c4c4;
}
```
