### ISSUE TITLE
Apply reusable GitHub workflow image-lint-scan.yml

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-portal#144]
Apply the reusable GitHub workflow `image-lint-scan.yml` to this repository on:
```yaml
on:
  pull_request:
    branches:
      - develop
      - master
```
