### ISSUE TITLE
Update paths event filter in pr-image.yml to all non-chart files.

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-portal#181]
Update the event in `.github/workflows/pr-image.yml` to something like:
```yaml
on:
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - ".github/**"
      - "resources/chart/**"
      - "resources/docs/**"
      - "resources/notebook/**"
```
