### ISSUE TITLE
Increase GKE Load balancer timeout to 10 minutes

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-portal#253]
In `./resources/chart/templates/gcp`:
```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
...
spec:
  ...
  timeoutSec: 600
```

* This relates to https://github.com/slateci/slate-client-server/issues/435.
* Adding @sthapa as a watcher.
