### ISSUE TITLE
CSS makes 'ul ul a' on page hard to read.

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-portal#283]
From `style.css:183`:
```css
ul ul a {
    font-size: 0.9em !important;
    padding-left: 30px !important;
    background: #6d7fcc;
}
```
![Screenshot_2023-05-24_14-31-47](https://github.com/slateci/slate-portal/assets/94396076/8e326d4d-0232-4e7f-8428-e3491c6f8f91)
